### ISSUE TITLE
Using scirpt in head does not correctly generate 

### ISSUE THREAD

**Issue by Sznymo** [RattleyCooper/PageCraft#1] opened 2024-08-04 15:35 UTC
Using scirpt in head does not correctly generate 
```
proc site*(content: string, menu: bool = true) {.htmlTemplate.} =
  let config: JsonNode = parseJson(readFile("config.json"))
  var lang: JsonNode = parseJson(readFile(getCurrentDir() / "data" / "lang" / config["language"].getstr & ".json"))

  html:
    head:
      title: 
        "Mod Managerr"
      script src="/webui.js"
      meta charset="UTF-8"
      meta name="google", content="notranslate"
      meta name="author", content="Sznymo"
      meta name="application-name", content="Pomocnik Tłumacza"
      meta name="viewport", content="width=device-width, initial-scale=1.0"
      link rel="icon", typee="image/png", sizes="32x32", href={"/data/themes/" & config["themes"].getStr & "/favicon.png"}
      link rel="stylesheet", href="/styles.css"

    body:
      if menu:
        divv class="menubar":
          span id="menu-toggle":
            "Vintage Story Launcher"
          nav id="menu":
            ul:
              li:
                a href="/index.html":
                  "Graj"
              li:
                a href="/installed_mods.html":
                  "Modyfikacje"
              li:
                a href="/options.html":
                  "Opcje"
              li:
                a href="/version_game.html":
                  "Wersje gry"
      {content}

      script:
        """
        document.getElementById('menu-toggle').addEventListener('click', function() {
          const menu = document.getElementById('menu');
          if (menu.classList.contains('hidden')) {
            menu.classList.remove('hidden');
          } else {
            menu.classList.add('hidden');
          }
        });
        """
```
it gives the effect 
```
<html>
  <head>
    <title>
      Mod Managerr
    </title>
    <script src="/webui.js" >
    <meta charset="UTF-8" >
    <meta name="google" content="notranslate" >
    <meta name="author" content="Sznymo" >
    <meta name="application-name" content="Pomocnik Tłumacza" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <link rel="icon" type="image/png" sizes="32x32" href="/data/themes/Vintage/favicon.png" >
    <link rel="stylesheet" href="/styles.css" >
  </head>
  <body>
    <div class="menubar" >
      <span id="menu-toggle" >
        Vintage Story Launcher
      </span>
      <nav id="menu" >
        <ul>
          <li>
            <a href="/index.html" >
              Graj
            </a>
          </li>
          <li>
            <a href="/installed_mods.html" >
              Modyfikacje
            </a>
          </li>
          <li>
            <a href="/options.html" >
              Opcje
            </a>
          </li>
          <li>
            <a href="/version_game.html" >
              Wersje gry
            </a>
          </li>
        </ul>
      </nav>
    </div>
        <div id="background-container"> 
      <img id="background-image"  src=/data/themes/Vintage/background_0.png>
    </div>
      <button id="run_game" class="run_game" type="submit">RUN</button>
    
    <script>
      document.getElementById('menu-toggle').addEventListener('click', function() {
          const menu = document.getElementById('menu');
          if (menu.classList.contains('hidden')) {
            menu.classList.remove('hidden');
          } else {
            menu.classList.add('hidden');
          }
        });
    </script>
  </body>
</html>
```
this is <script src="/webui.js"> and this is how it should be <script src='/webui.js'></script>.
because otherwise the site thinks the end of the script is at the bottom of the page

**Comment by RattleyCooper** [comment] 2024-08-06 03:28
So you can write `script src="/webui.js": “”` to force the creation of a closing tag, and:

`script src="/webui.js"`
`/script`

works as well.

I need to add this to the documentation.  Thank you for bringing it to my attention.

this is the intended behavior, I just didn’t document the behavior related to forcing the creation of closing tags

**Closed as completed** 2024-08-06 03:30 UTC
